---
title: "Report"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache = FALSE)
```

## R Markdown


```{r, prepare, include=FALSE}
library(dplyr)
library(stringr)
library(stringi)
library(ggplot2)
library(pkgcond)
library(kableExtra)
data_dir <- "../Data/"
dataset <- 'GD45'
myresults_file <- paste0(data_dir,'/',dataset,'/','myresults.rds')
results <- as.data.frame(readRDS(paste0(data_dir,'/',dataset,'/','results.rds')))
names(results) = "Results"
confusion_matrix <- readRDS(paste0(data_dir,'/',dataset,'/','confusion_matrix.rds'))
confusion_plot <- readRDS(paste0(data_dir,'/',dataset,'/','confusion_plot.rds'))
placenames <- readRDS(paste0(data_dir,'/',dataset,'/','placenames.rds'))
interesting_data <- readRDS(paste0(data_dir,'/',dataset,'/','interesting_data.rds'))
text <- interesting_data[['text']]

get_full_placenames <- function(placenames) {

pred1 <- placenames[-1,] %>% select(word,predictions)
pred1[nrow(pred1)+1,] <- NA
names(pred1) <- c('word1','pred1')
pred2 <- pred1[-1,]
pred2[nrow(pred2)+1,] <- NA
names(pred2) <- c('word2','pred2')
pred3 <- pred2[-1,]
pred3[nrow(pred3)+1,] <- NA
names(pred3) <- c('word3','pred3')
full_placenames <- unique(unique(cbind(placenames,pred1,pred2,pred3)) %>%
  filter(predictions == "GPE_B",
         word1 != word2 ) %>%
  mutate(name = ifelse(pred1 == "GPE_I",paste(word,word1),word),
         name = ifelse(pred1 == "GPE_I" & pred2 == "GPE_I",paste(word,word1,word2),name),
         name = ifelse(pred1 == "GPE_I" & pred2 == "GPE_I" & pred3 == "GPE_I", paste(word,word1,word2,word3),name)) %>%
  select(name))
full_placenames <- mutate(full_placenames,tname = paste0('\\W',name,'\\W'),
                          no_of_words = sapply(strsplit(name, " "), length),
                          no_of_characters = nchar(name)) %>%
                          arrange(desc(no_of_words),desc(no_of_characters))
a <- as.character(full_placenames$name)
a <- as.character(a)
a <- regex(a, ignore_case = TRUE)
return(a)
}


clean <- function(value,a) {
  b <- str_extract(value,a)
  b <- b[!is.na(b)]
  #b <- ifelse(identical(b, character()),"",b)
  b <- paste(b, collapse = ",")
  b
  return(b)
}

a <- get_full_placenames(placenames)
myresults <- unlist(lapply(text$value, function(x) clean(x,a)),recursive = FALSE)
myresults <- as.data.frame(cbind(text,myresults))
names(myresults) <- c("Ref","Type","Text","Locations")
saveRDS(myresults, myresults_file)


```

```{r, 'reports', message=FALSE, warning=FALSE, results='asis', echo = FALSE, cache = FALSE}
#placenames$word
options(scipen=999)
results %>%
  kbl() %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed")) %>%
  row_spec(1:nrow(results),color='black')
confusion_plot
#knitr::kable(tester, caption = dataset)


display <- slice(myresults,1:20)
#display <- myresults
display %>%
  kbl() %>%
 # kable_styling(bootstrap_options = c("striped")) %>%
#  row_spec(1:nrow(display),color='black') %>%
  column_spec(1,width = "1cm") %>%
  column_spec(2,width = "1cm") %>%
  column_spec(3,width = "5cm") %>%
  column_spec(4,width = "2cm")
```


z <- myresults[[1:10]]